# Generated by Django 5.1.1 on 2024-09-19 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyomaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyomaa_nro', models.CharField(max_length=10)),
                ('alku_pvm', models.DateField()),
                ('loppu_pvm', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tyontekija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kalusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laite', models.CharField(max_length=100)),
                ('sarja_nro', models.CharField(max_length=100)),
                ('kuva', models.ImageField(blank=True, null=True, upload_to='kuvat/')),
                ('tila', models.CharField(choices=[('EHJA', 'Ehjä'), ('RIKKI', 'Rikki'), ('KAYTOSSA', 'Käytössä'), ('VAPAA', 'Vapaa'), ('HUOLLOSSA', 'Huollossa')], max_length=10)),
                ('tyomaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sijainti.tyomaa')),
                ('kayttaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sijainti.tyontekija')),
            ],
        ),
    ]
