# Generated by Django 5.1.1 on 2024-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalusto',
            name='tila',
            field=models.CharField(choices=[('EHJÄ', 'Ehjä'), ('RIKKI', 'Rikki'), ('KÄYTÖSSÄ', 'Käytössä'), ('VAPAA', 'Vapaa'), ('HUOLLOSSA', 'Huollossa')], max_length=10),
        ),
    ]
