# Generated by Django 5.1.1 on 2024-09-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0004_alter_tyontekija_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyontekija',
            name='user',
        ),
    ]
