# Generated by Django 5.1.1 on 2024-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0006_tyontekija_is_active_tyontekija_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyontekija',
            name='password2',
            field=models.CharField(max_length=150),
        ),
    ]
