# Generated by Django 5.1.1 on 2024-09-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0007_alter_tyontekija_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyontekija',
            name='password2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
