# Generated by Django 5.1.1 on 2024-09-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0008_alter_tyontekija_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyontekija',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tyontekija',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='tyontekija',
            name='password2',
            field=models.CharField(max_length=150),
        ),
    ]
