# Generated by Django 5.1.1 on 2024-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0010_alter_tyontekija_password1_alter_tyontekija_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyontekija',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
