# Generated by Django 5.1.1 on 2024-09-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0011_alter_tyontekija_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyontekija',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
