# Generated by Django 5.1.1 on 2024-09-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0012_alter_tyontekija_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyontekija',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tyontekija',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
