# Generated by Django 5.1.1 on 2024-09-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sijainti', '0013_tyontekija_is_active_tyontekija_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyontekija',
            name='password2',
        ),
    ]
